// Pure Dart S7comm tag<->area/offset map model (S7comm workstream).
//
// Mirrors the Modbus register map (modbus_map.dart), which solves the same
// named-tag <-> numeric-address problem, but with one fundamental
// difference: S7comm addresses a BYTE RANGE inside a memory area, not a
// discrete register or point. A real S7 driver issues optimized block reads
// ("DB1 bytes 0..40" in one request), so tags must be packed into a byte
// image — see protocols/s7/s7_area_image.dart, which consumes this map.
//
// Areas supported in v1: `'DB'` (data block), `'M'` (merker/flag), `'I'`
// (process inputs) and `'Q'` (process outputs). Timer and counter areas are
// deliberately NOT supported: they use S5TIME/BCD encodings with no
// equivalent in this app's tag model.
//
// Type mapping (see s7_area_image.dart for the encoding itself):
//   BOOL    -> 1 bit
//   INT16   -> INT,  2 bytes
//   INT32   -> DINT, 4 bytes
//   INT64   -> LINT, 8 bytes
//   FLOAT64 -> REAL, 4 bytes — a NARROWING conversion to IEEE-754 single
//              precision. The app stores doubles; S7 REAL is 32-bit, so a
//              value read back over S7comm is the float32 approximation of
//              the tag's value, not the double itself.
//   STRING  -> SKIPPED by [S7Map.autoGenerate]. An S7 STRING is a struct
//              carrying max-length and actual-length header bytes ahead of
//              its characters; supporting it properly is deferred to v2.
//              A STRING can still be mapped by hand, but the area image
//              refuses to encode or decode it.
//
// No Flutter dependency and no dart:io — this file must stay pure Dart so it
// can be used from services and widgets alike.

import 'project_model.dart';
import 'tag_resolver.dart';

/// Data-block area code.
const String kS7AreaNameDb = 'DB';

/// Merker (flag) area code.
const String kS7AreaNameMerker = 'M';

/// Process-inputs area code.
const String kS7AreaNameInputs = 'I';

/// Process-outputs area code.
const String kS7AreaNameOutputs = 'Q';

/// Every area name this version supports.
const List<String> kS7AreaNames = [
  kS7AreaNameDb,
  kS7AreaNameMerker,
  kS7AreaNameInputs,
  kS7AreaNameOutputs,
];

/// The data block [S7Map.autoGenerate] packs every tag into.
const int kS7AutoGenerateDbNumber = 1;

/// One S7 map entry, binding a project tag (by its dotted/indexed leaf path)
/// to an `area` + `dbNumber` + `byteOffset` + `bitOffset` address.
///
/// `area` is one of [kS7AreaNames]. `dbNumber` is only meaningful when
/// `area == 'DB'`; it is stored (and serialized) as 0 for the other areas.
/// `bitOffset` is only meaningful for `BOOL` tags and is 0 otherwise.
/// `access` is either `'ReadOnly'` or `'ReadWrite'`.
class S7MapEntry {
  String tag;
  String area;
  int dbNumber;
  int byteOffset;
  int bitOffset;
  String access;

  S7MapEntry({
    required this.tag,
    required this.area,
    required this.dbNumber,
    required this.byteOffset,
    this.bitOffset = 0,
    this.access = 'ReadWrite',
  });

  factory S7MapEntry.fromJson(Map<String, dynamic> json) => S7MapEntry(
        tag: json['tag']?.toString() ?? '',
        area: json['area']?.toString() ?? kS7AreaNameDb,
        dbNumber: (json['db_number'] as num?)?.toInt() ?? 0,
        byteOffset: (json['byte_offset'] as num?)?.toInt() ?? 0,
        bitOffset: (json['bit_offset'] as num?)?.toInt() ?? 0,
        access: json['access']?.toString() ?? 'ReadWrite',
      );

  Map<String, dynamic> toJson() => {
        'tag': tag,
        'area': area,
        'db_number': dbNumber,
        'byte_offset': byteOffset,
        'bit_offset': bitOffset,
        'access': access,
      };
}

/// The editable S7 area map for a project: the list of tag<->address
/// bindings across the supported memory areas.
class S7Map {
  List<S7MapEntry> entries;

  S7Map({List<S7MapEntry>? entries}) : entries = entries ?? [];

  /// Tolerant of a missing or non-list `entries` key so an older project
  /// JSON with no `s7` section loads cleanly (additive persistence).
  factory S7Map.fromJson(Map<String, dynamic> json) {
    final rawEntries = json['entries'];
    return S7Map(
      entries: (rawEntries is List)
          ? rawEntries
              .whereType<Map>()
              .map((e) => S7MapEntry.fromJson(Map<String, dynamic>.from(e)))
              .toList()
          : <S7MapEntry>[],
    );
  }

  Map<String, dynamic> toJson() => {
        'entries': entries.map((e) => e.toJson()).toList(),
      };

  /// Width in bytes a scalar data type occupies in an S7 area image, or
  /// `null` if the type has no v1 S7 representation (`STRING`, and anything
  /// unrecognized). `BOOL` reports 1 because it lives inside exactly one
  /// byte, even though it only occupies a single bit of it.
  static int? widthBytesForType(String dataType) {
    switch (dataType) {
      case 'BOOL':
        return 1;
      case 'INT16':
        return 2;
      case 'INT32':
        return 4;
      case 'FLOAT64':
        return 4; // REAL — narrowing, see the file header.
      case 'INT64':
        return 8;
      default:
        return null;
    }
  }

  /// Natural alignment, in bytes, for a scalar data type: 2-byte types sit
  /// on even offsets, and 4- and 8-byte types on 4-byte boundaries. `BOOL`
  /// is bit-packed and has no byte alignment requirement.
  static int alignmentForType(String dataType) {
    switch (dataType) {
      case 'INT16':
        return 2;
      case 'INT32':
      case 'INT64':
      case 'FLOAT64':
        return 4;
      default:
        return 1;
    }
  }

  /// Builds a default map from a project's scalar leaf tags
  /// ([scalarLeaves]): composite/array tags are expanded into one entry per
  /// scalar leaf. Every entry is packed into `DB`
  /// [kS7AutoGenerateDbNumber] with natural alignment, in leaf order.
  ///
  /// `BOOL` leaves are bit-packed: consecutive BOOLs share a byte, filling
  /// bits 0..7 before advancing. The first non-BOOL leaf after a BOOL closes
  /// the partially used byte and then aligns per [alignmentForType].
  ///
  /// `STRING` leaves are SKIPPED entirely (see the file header), as is any
  /// other type with no [widthBytesForType].
  ///
  /// Access is inherited from the ROOT tag (the tag whose name is the leaf
  /// path's first segment), exactly as the Modbus and CIP maps do: an
  /// `ioType` of `'SimulatedOutput'` or an explicit tag `access` of
  /// `'ReadOnly'` (which is how the reserved `System` tag is marked) yields
  /// `'ReadOnly'`; everything else yields `'ReadWrite'`.
  static S7Map autoGenerate(PlcProject p) {
    final entries = <S7MapEntry>[];
    var nextByte = 0;
    var nextBit = 0;
    for (final leaf in scalarLeaves(p)) {
      final width = widthBytesForType(leaf.dataType);
      if (width == null) {
        continue;
      }
      final root = rootTagOf(p, leaf.path);
      final rw = root?.ioType != 'SimulatedOutput' && root?.access != 'ReadOnly';
      final access = rw ? 'ReadWrite' : 'ReadOnly';

      int byteOffset;
      int bitOffset;
      if (leaf.dataType == 'BOOL') {
        byteOffset = nextByte;
        bitOffset = nextBit;
        nextBit += 1;
        if (nextBit >= 8) {
          nextBit = 0;
          nextByte += 1;
        }
      } else {
        // Close any partially used bit byte before taking whole bytes.
        if (nextBit > 0) {
          nextBit = 0;
          nextByte += 1;
        }
        final align = alignmentForType(leaf.dataType);
        if (align > 1 && nextByte % align != 0) {
          nextByte += align - (nextByte % align);
        }
        byteOffset = nextByte;
        bitOffset = 0;
        nextByte += width;
      }

      entries.add(S7MapEntry(
        tag: leaf.path,
        area: kS7AreaNameDb,
        dbNumber: kS7AutoGenerateDbNumber,
        byteOffset: byteOffset,
        bitOffset: bitOffset,
        access: access,
      ));
    }
    return S7Map(entries: entries);
  }
}
