//! Machine-proof that a REAL, independent, third-party Modbus TCP client
//! (the `tokio-modbus` crate's own client — not anything hand-rolled by the
//! Dart side) can read from and write to the in-app pure-Dart Modbus TCP
//! server (WS24 Tasks 1-3, `mobile/lib/models/modbus_map.dart` +
//! `mobile/lib/protocols/modbus/modbus_pdu.dart` +
//! `mobile/lib/services/modbus_host.dart`).
//!
//! Usage:
//!   cargo run --manifest-path gateway/Cargo.toml --example modbus_probe -- 127.0.0.1 <port>
//!
//! Talks to a server hosting a small fixture project with three mapped tags
//! (see `mobile/tool/modbus_host_probe.dart`, which this probe is designed
//! to run against via `tool/modbus_e2e.sh`):
//!   - `Start_PB`    : BOOL,  ReadWrite -> coil address 0
//!   - `Forced_Bool` : BOOL,  ReadWrite -> coil address 1, `isForced: true`,
//!     `forcedValue: true` (Task 4 forced-coil-reads-through proof; the
//!     tag's live `value` is `false`)
//!   - `Speed`       : INT16, ReadWrite -> holding register address 0
//!   - `Motor.Speed` : INT32 struct member -> holding registers 1-2 (Task 4
//!     struct-member-decodes-correctly proof)
//!   - `Temp`        : INT16, ReadOnly  -> input register address 0 (unused
//!     by this probe; present so the fixture map exercises all four Modbus
//!     data tables, per the docs' 4-table mapping)
//!   - `Ramp1`/`Ramp2` : FLOAT64, ReadOnly -> input registers 4-7 / 8-11 --
//!     two `SimulatedOutput` tags generated by `buildTestSet` (a `ramp`
//!     signal, range [0,1000], period 20s, phase-staggered 0.5 apart) and
//!     appended onto the map by `appendToModbusMap`; driven every 100ms by
//!     `applySignalGens` on the Dart side (simulated-test-tags workstream,
//!     Task 8 E2E machine-proof).
//!
//! Steps:
//!   1. Connect a TCP context to `host:port` (no unit-id framing beyond the
//!      default `Slave::tcp_device()` — this is a direct Modbus TCP
//!      connection, not routed through a gateway).
//!   2. Poll `read_holding_registers(0, 1)` (bounded) until it reads back
//!      `4242` — the value the Dart fixture host's own timer mutates
//!      holding-register 0 to at T+3s after printing `READY`, entirely
//!      independently of this client. Observing that value can only mean
//!      this probe is reading the *live* register file, not a frozen
//!      snapshot taken at connect time.
//!   3. `write_single_register(0, 7777)` then read the same register back
//!      and assert it now reads `7777` — proof the write actually landed in
//!      the server's tag database (verified by an independent Read, not the
//!      write's own echo response).
//!   4. `write_single_coil(0, true)` then `read_coils(0, 1)` and assert
//!      `[true]` — same proof, for the bit-table side of the map.
//!   5. `read_coils(1, 1)` and assert `[true]` — the falsifiable proof that
//!      `Forced_Bool`'s `isForced`/`forcedValue` state reaches Modbus reads:
//!      the tag's live `value` is `false`, so this only reads `true` if the
//!      force-aware `readPath` resolver (shared with the scan engine and the
//!      OPC UA server) is actually being consulted by the Modbus register
//!      handler.
//!   5b. `write_single_coil(1, false)` on that SAME forced coil and assert
//!      the call returns `Err(ExceptionCode::IllegalDataAddress)`, NOT
//!      `Ok(())` — the protocol-hardening workstream's Task 3 machine-proof.
//!      Before Task 3 this write was silently discarded server-side but
//!      still answered with a normal success echo (a deceptive-success bug:
//!      the master believed its write landed when it never did). This step
//!      proves, via the REAL tokio-modbus client's own typed error, that (a)
//!      the server now answers a genuine Modbus exception PDU instead of a
//!      success echo, and (b) the chosen exception code (Illegal Data
//!      Address, `0x02` — the same code the ReadOnly/unmapped refusals
//!      already use) decodes cleanly through a third-party client rather
//!      than being misparsed, causing a protocol desync, or requiring
//!      special-case handling. A follow-up `read_coils(1, 1)` re-confirms
//!      the coil still reads `true` (forced value intact, never touched by
//!      the refused write).
//!   6. `read_holding_registers(1, 2)` and decode as a big-endian,
//!      high-word-first INT32, asserting it equals the `Motor.Speed`
//!      struct-member field's value — proof a dotted struct-member map entry
//!      resolves its type/value through the full path, not just a top-level
//!      tag name.
//!   7. `read_input_registers(4, 4)` and `read_input_registers(8, 4)`,
//!      decode each as a big-endian FLOAT64, and assert `Ramp1 != Ramp2` —
//!      the simulated-test-tags Task 8 machine-proof of phase-staggering:
//!      two tags generated from the same `ramp` `buildTestSet` spec, phase
//!      0 and phase 0.5, must read distinct live values at the same instant.
//!   8. Re-read `Ramp1` (input registers 4-7) after a short wall-clock wait
//!      and assert the decoded value changed from step 7's reading — proof
//!      the generated tag's value is actually advancing over time (driven by
//!      `applySignalGens` on a real per-tick clock), not a static seed value.
//! Prints `MODBUS PROBE PASS` and exits 0 on success; on any failure prints
//! `MODBUS PROBE FAIL: <reason>` and exits 1 — never panics past the top
//! level.
use std::env;
use std::net::SocketAddr;
use std::process::ExitCode;
use std::time::{Duration, Instant};

use tokio::time::{sleep, timeout};
use tokio_modbus::client::tcp::connect;
use tokio_modbus::client::Context;
use tokio_modbus::prelude::*;

/// Value the Dart fixture host (`mobile/tool/modbus_host_probe.dart`)
/// writes to holding-register 0 (the `Speed` tag) at T+3s after printing
/// `READY`, purely as a server-side mutation for this probe to observe (a
/// real "value changed on the device" push via polling, not a client
/// write).
const SERVER_MUTATED_HOLDING_VALUE: u16 = 4242;

/// Value this probe itself writes to holding-register 0 via FC06, then
/// reads back to verify the write landed.
const CLIENT_WRITTEN_HOLDING_VALUE: u16 = 7777;

/// How long to wait for the server-side mutation to become visible before
/// giving up. The Dart fixture host schedules it at a fixed T+3s, so this
/// generously covers connection + polling overhead.
const SERVER_MUTATION_WAIT: Duration = Duration::from_secs(10);

/// Per-call bound so a hung server can never make this probe (or the CI
/// job wrapping it) block forever.
const CALL_TIMEOUT: Duration = Duration::from_secs(5);

/// Coil address of `Forced_Bool` in the Dart fixture host's map (see
/// `mobile/tool/modbus_host_probe.dart`), a tag whose live `value` is
/// `false` but whose `isForced`/`forcedValue` mark it force-read as `true`
/// — reading `true` here is only possible if the force-aware resolver is
/// actually consulted by the Modbus register handler.
const FORCED_COIL_ADDR: u16 = 1;

/// Holding-register address of the `Motor.Speed` INT32 struct-member map
/// entry (occupies 2 registers: `STRUCT_MEMBER_HOLDING_ADDR` and
/// `STRUCT_MEMBER_HOLDING_ADDR + 1`, high-word-first).
const STRUCT_MEMBER_HOLDING_ADDR: u16 = 1;

/// Expected decoded value of `Motor.Speed`, matching the Dart fixture
/// host's `_structMemberSpeedValue`.
const STRUCT_MEMBER_EXPECTED_VALUE: i32 = 9001;

/// Input-register base addresses of the two generated `ramp` test-set tags
/// (simulated-test-tags Task 8), matching the Dart fixture host's
/// `rampInputAddr1`/`rampInputAddr2` constants (`mobile/tool/
/// modbus_host_probe.dart`) — see that file's doc comment for how these
/// addresses are derived from `appendToModbusMap`'s bookkeeping.
const RAMP1_INPUT_ADDR: u16 = 4;
const RAMP2_INPUT_ADDR: u16 = 8;

/// A FLOAT64 test-set tag occupies 4 consecutive 16-bit registers.
const RAMP_REG_COUNT: u16 = 4;

/// Wall-clock gap between the two `Ramp1` reads in step 8. The Dart side's
/// `ramp` tag spans [0,1000] over a 20s period, so this gap alone should
/// move the value by roughly `1000 * 300/20000 = 15` — comfortably above any
/// floating-point or scheduling noise.
const RAMP_MOVE_WAIT: Duration = Duration::from_millis(300);

async fn read_holding(ctx: &mut Context, addr: u16, cnt: u16) -> Result<Vec<u16>, String> {
    timeout(CALL_TIMEOUT, ctx.read_holding_registers(addr, cnt))
        .await
        .map_err(|_| format!("read_holding_registers({addr},{cnt}) timed out"))?
        .map_err(|e| format!("read_holding_registers({addr},{cnt}) transport error: {e}"))?
        .map_err(|ex| format!("read_holding_registers({addr},{cnt}) exception: {ex}"))
}

async fn write_single_register(ctx: &mut Context, addr: u16, value: u16) -> Result<(), String> {
    timeout(CALL_TIMEOUT, ctx.write_single_register(addr, value))
        .await
        .map_err(|_| format!("write_single_register({addr},{value}) timed out"))?
        .map_err(|e| format!("write_single_register({addr},{value}) transport error: {e}"))?
        .map_err(|ex| format!("write_single_register({addr},{value}) exception: {ex}"))
}

async fn write_single_coil(ctx: &mut Context, addr: u16, value: bool) -> Result<(), String> {
    timeout(CALL_TIMEOUT, ctx.write_single_coil(addr, value))
        .await
        .map_err(|_| format!("write_single_coil({addr},{value}) timed out"))?
        .map_err(|e| format!("write_single_coil({addr},{value}) transport error: {e}"))?
        .map_err(|ex| format!("write_single_coil({addr},{value}) exception: {ex}"))
}

async fn read_coils(ctx: &mut Context, addr: u16, cnt: u16) -> Result<Vec<bool>, String> {
    timeout(CALL_TIMEOUT, ctx.read_coils(addr, cnt))
        .await
        .map_err(|_| format!("read_coils({addr},{cnt}) timed out"))?
        .map_err(|e| format!("read_coils({addr},{cnt}) transport error: {e}"))?
        .map_err(|ex| format!("read_coils({addr},{cnt}) exception: {ex}"))
}

async fn read_input(ctx: &mut Context, addr: u16, cnt: u16) -> Result<Vec<u16>, String> {
    timeout(CALL_TIMEOUT, ctx.read_input_registers(addr, cnt))
        .await
        .map_err(|_| format!("read_input_registers({addr},{cnt}) timed out"))?
        .map_err(|e| format!("read_input_registers({addr},{cnt}) transport error: {e}"))?
        .map_err(|ex| format!("read_input_registers({addr},{cnt}) exception: {ex}"))
}

/// Decodes 4 big-endian, high-word-first 16-bit registers back to a FLOAT64
/// — mirrors the Dart side's `decodeFloat64` with `wordSwap`/`byteSwap` both
/// false (the fixture project sets neither), i.e. the IEEE-754 double's 8
/// bytes packed MSB-register-first.
fn decode_float64_be(regs: &[u16]) -> f64 {
    let mut bits: u64 = 0;
    for r in regs {
        bits = (bits << 16) | (*r as u64);
    }
    f64::from_bits(bits)
}

async fn run(host: &str, port: u16) -> Result<(), String> {
    let addr: SocketAddr = format!("{host}:{port}")
        .parse()
        .map_err(|e| format!("bad address {host}:{port}: {e}"))?;

    println!("[probe] connecting to {addr}...");
    let mut ctx = timeout(Duration::from_secs(10), connect(addr))
        .await
        .map_err(|_| "connect timed out".to_string())?
        .map_err(|e| format!("connect failed: {e}"))?;
    println!("[probe] connected.");

    // --- Step 1: poll for the server-side mutation of holding[0] ---------
    println!(
        "[probe] polling holding[0] (up to {:?}) for the server-side mutation to {SERVER_MUTATED_HOLDING_VALUE}...",
        SERVER_MUTATION_WAIT
    );
    let deadline = Instant::now() + SERVER_MUTATION_WAIT;
    let mut last_seen: Vec<u16>;
    let mut observed = false;
    loop {
        let regs = read_holding(&mut ctx, 0, 1).await?;
        last_seen = regs.clone();
        if regs.first().copied() == Some(SERVER_MUTATED_HOLDING_VALUE) {
            observed = true;
            break;
        }
        if Instant::now() >= deadline {
            break;
        }
        sleep(Duration::from_millis(200)).await;
    }
    if !observed {
        return Err(format!(
            "timed out after {SERVER_MUTATION_WAIT:?} waiting for holding[0] == {SERVER_MUTATED_HOLDING_VALUE}, last saw {last_seen:?}"
        ));
    }
    println!("[probe] observed server-side mutation: holding[0] = {SERVER_MUTATED_HOLDING_VALUE}");

    // --- Step 2: write_single_register(0, 7777) then read back -----------
    println!("[probe] write_single_register(0, {CLIENT_WRITTEN_HOLDING_VALUE})...");
    write_single_register(&mut ctx, 0, CLIENT_WRITTEN_HOLDING_VALUE).await?;
    println!("[probe] write OK; reading holding[0] back to verify...");
    let regs = read_holding(&mut ctx, 0, 1).await?;
    match regs.first().copied() {
        Some(v) if v == CLIENT_WRITTEN_HOLDING_VALUE => {
            println!("[probe] read-back OK: holding[0] = {v}");
        }
        other => {
            return Err(format!(
                "expected holding[0] == {CLIENT_WRITTEN_HOLDING_VALUE} after the write, got {other:?}"
            ))
        }
    }

    // --- Step 3: write_single_coil(0, true) then read_coils(0, 1) --------
    println!("[probe] write_single_coil(0, true)...");
    write_single_coil(&mut ctx, 0, true).await?;
    println!("[probe] write OK; reading coil[0] back to verify...");
    let coils = read_coils(&mut ctx, 0, 1).await?;
    match coils.first().copied() {
        Some(true) => println!("[probe] read-back OK: coil[0] = true"),
        other => {
            return Err(format!("expected coil[0] == Some(true) after the write, got {other:?}"))
        }
    }

    // --- Step 4: read the forced coil and assert it reads back forced -----
    //
    // `Forced_Bool`'s live tag `value` is `false` -- a read that returns
    // `true` here can only mean the Modbus register-file handler resolved
    // the read through the same force-aware `readPath` the scan engine and
    // OPC UA server use, not the tag's raw underlying value. This is the
    // falsifiable machine-proof (Task 4 of "Protocol Interop Fixes") that a
    // force set in the app is actually visible over Modbus.
    println!("[probe] read_coils({FORCED_COIL_ADDR}, 1) -- expect the forced value true...");
    let forced_coils = read_coils(&mut ctx, FORCED_COIL_ADDR, 1).await?;
    match forced_coils.first().copied() {
        Some(true) => println!(
            "[probe] forced-coil read OK: coil[{FORCED_COIL_ADDR}] = true (force reached Modbus)"
        ),
        other => {
            return Err(format!(
                "expected coil[{FORCED_COIL_ADDR}] == Some(true) (Forced_Bool's forced value read through to Modbus), got {other:?}"
            ))
        }
    }

    // --- Step 4b: write to the SAME forced coil must be REFUSED -----------
    //
    // Protocol-hardening workstream, Task 3 machine-proof. Before this fix,
    // a write to a forced tag was silently discarded server-side but the
    // server still answered with a normal SUCCESS echo -- a
    // deceptive-success bug: the master believed its write landed when it
    // never did. This step drives the REAL tokio-modbus client's own
    // `write_single_coil` and inspects its typed result directly (not the
    // string-collapsing helpers above) so a transport-level failure, a
    // silent success, and a genuine Modbus exception are all distinguishable
    // -- only the last is correct now.
    println!(
        "[probe] write_single_coil({FORCED_COIL_ADDR}, false) on the FORCED coil -- expect a Modbus exception, not success..."
    );
    match timeout(CALL_TIMEOUT, ctx.write_single_coil(FORCED_COIL_ADDR, false)).await {
        Err(_) => return Err(format!("write_single_coil({FORCED_COIL_ADDR}) timed out")),
        Ok(Err(transport_err)) => {
            return Err(format!(
                "write_single_coil({FORCED_COIL_ADDR}) transport error (expected a clean Modbus exception instead): {transport_err}"
            ));
        }
        Ok(Ok(Ok(()))) => {
            return Err(format!(
                "write_single_coil({FORCED_COIL_ADDR}) SUCCEEDED (Ok) -- this is the deceptive-success bug Task 3 fixes; a forced-tag write must be refused with a Modbus exception, not silently accepted"
            ));
        }
        Ok(Ok(Err(exception))) => {
            if exception != ExceptionCode::IllegalDataAddress {
                return Err(format!(
                    "expected ExceptionCode::IllegalDataAddress for a forced-tag write, got {exception:?}"
                ));
            }
            println!(
                "[probe] forced-write refusal OK: server answered Modbus exception {exception:?} (0x{:02X}), not a success echo",
                u8::from(exception)
            );
        }
    }
    // Re-read the forced coil to confirm the refused write never touched
    // the underlying value -- it must still read the forced `true`.
    let still_forced = read_coils(&mut ctx, FORCED_COIL_ADDR, 1).await?;
    match still_forced.first().copied() {
        Some(true) => println!(
            "[probe] forced coil still reads true after the refused write (unchanged, as expected)"
        ),
        other => {
            return Err(format!(
                "expected coil[{FORCED_COIL_ADDR}] to remain Some(true) after the refused write, got {other:?}"
            ));
        }
    }

    // --- Step 5: read the struct-member holding registers and decode -------
    //
    // `Motor.Speed` is a dotted struct-member map entry (an INT32 field of
    // the `Motor` tag's `MotorType` struct), occupying 2 holding registers.
    // Decoding the correct value at the correct width proves the register
    // handler resolves a struct-member path's type/value through the full
    // dotted path, not just by matching the map entry's `tag` string against
    // top-level tag names (which would silently fall back to a wrong width
    // or wrong value).
    println!(
        "[probe] read_holding_registers({STRUCT_MEMBER_HOLDING_ADDR}, 2) -- struct member Motor.Speed (INT32)..."
    );
    let motor_regs = read_holding(&mut ctx, STRUCT_MEMBER_HOLDING_ADDR, 2).await?;
    if motor_regs.len() != 2 {
        return Err(format!(
            "expected 2 registers reading Motor.Speed, got {} ({:?})",
            motor_regs.len(),
            motor_regs
        ));
    }
    // Big-endian, high-word-first per the docs' encoding rules.
    let motor_speed = ((motor_regs[0] as u32) << 16 | motor_regs[1] as u32) as i32;
    if motor_speed != STRUCT_MEMBER_EXPECTED_VALUE {
        return Err(format!(
            "expected Motor.Speed == {STRUCT_MEMBER_EXPECTED_VALUE}, decoded {motor_speed} from registers {motor_regs:?}"
        ));
    }
    println!("[probe] struct-member read OK: Motor.Speed = {motor_speed}");

    // --- Step 7: read both phase-staggered generated ramp tags ------------
    //
    // `Ramp1` (phase 0) and `Ramp2` (phase 0.5) are generated by the same
    // `buildTestSet` `ramp` spec on the Dart side and appended onto this
    // same Modbus map via `appendToModbusMap` -- reading distinct values at
    // the same instant is the falsifiable machine-proof (simulated-test-tags
    // Task 8) that bulk-generated test tags are actually phase-staggered
    // over the wire, not just in the in-app model.
    println!(
        "[probe] read_input_registers({RAMP1_INPUT_ADDR}, {RAMP_REG_COUNT}) -- generated ramp tag Ramp1..."
    );
    let ramp1_regs_a = read_input(&mut ctx, RAMP1_INPUT_ADDR, RAMP_REG_COUNT).await?;
    let ramp1_a = decode_float64_be(&ramp1_regs_a);
    println!("[probe] Ramp1 sample 1 = {ramp1_a}");

    println!(
        "[probe] read_input_registers({RAMP2_INPUT_ADDR}, {RAMP_REG_COUNT}) -- generated ramp tag Ramp2 (phase-staggered 0.5)..."
    );
    let ramp2_regs = read_input(&mut ctx, RAMP2_INPUT_ADDR, RAMP_REG_COUNT).await?;
    let ramp2 = decode_float64_be(&ramp2_regs);
    println!("[probe] Ramp2 = {ramp2}");

    if (ramp1_a - ramp2).abs() < 1e-9 {
        return Err(format!(
            "expected Ramp1 ({ramp1_a}) != Ramp2 ({ramp2}) -- phase-staggered generated test-set tags read identical values"
        ));
    }
    println!("[probe] phase-stagger OK: Ramp1 ({ramp1_a}) != Ramp2 ({ramp2})");

    // --- Step 8: re-read Ramp1 after a wall-clock gap and assert it moved --
    //
    // Proof (simulated-test-tags Task 8) that the generated tag's value is
    // actually advancing over real time -- driven by `applySignalGens` on a
    // real per-tick clock on the Dart side -- not a static seed value that
    // merely differs between two tags at t=0.
    println!(
        "[probe] waiting {RAMP_MOVE_WAIT:?} then re-reading Ramp1 to prove its generated value is moving..."
    );
    sleep(RAMP_MOVE_WAIT).await;
    let ramp1_regs_b = read_input(&mut ctx, RAMP1_INPUT_ADDR, RAMP_REG_COUNT).await?;
    let ramp1_b = decode_float64_be(&ramp1_regs_b);
    println!("[probe] Ramp1 sample 2 = {ramp1_b}");
    if (ramp1_b - ramp1_a).abs() < 1e-9 {
        return Err(format!(
            "expected Ramp1 to move between reads {RAMP_MOVE_WAIT:?} apart, but sample1={ramp1_a} sample2={ramp1_b} (identical -- generated signal is not advancing)"
        ));
    }
    println!(
        "[probe] generated-signal movement OK: Ramp1 moved {ramp1_a} -> {ramp1_b} over {RAMP_MOVE_WAIT:?}"
    );

    if let Err(e) = ctx.disconnect().await {
        // Non-fatal: every assertion above already passed, and a clean
        // disconnect failing doesn't mean the protocol behavior was wrong.
        println!("[probe] (non-fatal) disconnect error: {e}");
    }

    Ok(())
}

#[tokio::main]
async fn main() -> ExitCode {
    let args: Vec<String> = env::args().collect();
    let host = match args.get(1) {
        Some(h) => h.clone(),
        None => {
            eprintln!("usage: modbus_probe <host> <port>");
            println!("MODBUS PROBE FAIL: missing host argument");
            return ExitCode::FAILURE;
        }
    };
    let port: u16 = match args.get(2).and_then(|p| p.parse().ok()) {
        Some(p) => p,
        None => {
            eprintln!("usage: modbus_probe <host> <port>");
            println!("MODBUS PROBE FAIL: missing or invalid port argument");
            return ExitCode::FAILURE;
        }
    };

    match run(&host, port).await {
        Ok(()) => {
            println!("MODBUS PROBE PASS");
            ExitCode::SUCCESS
        }
        Err(reason) => {
            println!("MODBUS PROBE FAIL: {reason}");
            ExitCode::FAILURE
        }
    }
}
